### ISSUE TITLE
Doesn't allow sanic >= 19.0

### ISSUE THREAD

**Issue by sallas** [trustpilot/python-sanicargs#12]
After the switch to poetry only sanic version >=18.12,<19.0 is allowed.

Error from poetry when trying to install sanicargs with sanic >19

[SolverProblemError]
Because sanicargs (2.0.0) depends on sanic (>=18.12,<19.0)
 and -my package- depdends on sanic (19.12.2), sanicargs is forbidden.

**Comment by thomasthiebaud** [comment]
That should be fixed by the latest version
