### ISSUE TITLE
don't impose request as first args

### ISSUE THREAD

**Issue by RemiDesgrange** [trustpilot/python-sanicargs#2]
I can see here : https://github.com/trustpilot/python-sanicargs/blob/master/sanicargs/__init__.py#L60 that naming the first args `request` is mandatory. 

What do you think about checking that the first args is an instance of `sanic.request` ?

**Comment by sloev** [comment]
Good idea! 
Can you make a pull request?

**Comment by sloev** [comment]
@RemiDesgrange 
I've had time to look at the issue and i disagree that it is better to be flexible here.
Sanic framework is imposing the same behaviour on the path params:
request is first param, after that comes path params (see https://github.com/channelcat/sanic/blob/master/docs/sanic/routing.md#request-parameters) 
So i think the `query params` should do the same.

What is your thoughts Remi?

**Comment by RemiDesgrange** [comment]
My proposal was to keep `sanic.request` instance as the first argument, but the name, should be changeable like:

```python
from sanic import request
from sanic.response import json as resjson

@app.route('/<id:int>')
async def index(req: request, id: int) -> resjson:
    return resjson({'id': id, 'headers': req.json}
```

**Comment by sloev** [comment]
@RemiDesgrange 
like in this PR:
https://github.com/trustpilot/python-sanicargs/pull/3
check the diff files to see how its used in the tests

**Comment by sloev** [comment]
fixed in #3

**Comment by RemiDesgrange** [comment]
Thanks !!! didn't see your notification, sorry

**Comment by sloev** [comment]
@RemiDesgrange hope it suits your usecase. Please report if you find anything else. 

- jgv

**Comment by RemiDesgrange** [comment]
👌👌👌
